# Ce fichier sert de modèle pour les fichiers compose qui se trouvent dans la VM
# Il n'est pas utilisé dans la base de code, il faut le copier et le compléter sur la VM

services:
    app:
        container_name: jc-app
        image: $USERNAME/jet-centre:prod # Compléter USERNAME et changer prod en preprod si besoin
        env_file:
            - .env.production
        environment:
            - NODE_ENV=production

        restart: always
        ports:
            - '[::]:8000:3000' # C'est 8010:3000 sur preprod
        networks:
            - db-network
            - internet
        depends_on:
            - postgres

    postgres:
        image: postgres:15
        container_name: jc-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: maindb
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - db-network
    watchtower:
        container_name: watchtower
        image: containrrr/watchtower
        restart: always
        environment:
            - WATCHTOWER_CLEANUP=true
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ~/.docker/config.json:/config.json:ro
        command: --interval 30 jc-app # On peut faire varier la durée de l'intervalle (actuellement c'est 900 sur preprod)

networks:
    db-network:
        external: false
    internet:
        enable_ipv6: true

volumes:
    postgres:
    bun-cache:
    app-data:
